### PR TITLE
Basic example fix #1426

### LINKED ISSUE #1426: 'ChatBot' object has no attribute 'find'
File "/usr/local/lib/python3.6/dist-packages/chatterbot/trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
AttributeError: 'ChatBot' object has no attribute 'find'

why?

### PR DESCRIPTION
**Pull request by MartinDelille**
This is an attempt to fix the error in `examples/basic example.py`.

It now runs but the answer to the question *I would like to book a flight.* is strange: *Much the same as being a human, except that we lack all emotions, dreams, aspirations, creativity, ambition, and above all subjectivity.*

It looks like it has been ask *Hello, how are you today?*

### CODE REVIEW

**Comment by vkosuri** [comment]
The example is a valid one, If you want to propose corpus example you could do propose ``basic_list_example`` and ``basic_corpus_example``

**Comment by MartinDelille** [comment]
@vkosuri Ok your right. I just edit it to make `basic_example.py` work on my side. Am I wrong?

**Comment by MartinDelille** [comment]
@gunthercox why did you closed the PR without reason?

**Comment by gunthercox** [comment]
@MartinDelille Thank you for asking. I must have misread your comment that you left above and though that you had decided that this was not a correct change.

> Ok your right. I just edit it to make basic_example.py work on my side. Am I wrong?

I did check over your code and I saw that the change was the following:

```diff
- trainer = ListTrainer(chatbot)
+ # Create a new trainer for the chatbox
+ trainer = ListTrainer(chatbot.storage)
```

This change would break the existing example since it expects a `ChatBot` instance to be passed in instead of a storage adapter.

```
# trainers.py
    def __init__(self, chatbot, **kwargs):
        self.chatbot = chatbot
```

**Comment by MartinDelille** [comment]
The problem is that if I don't apply this modification I have the following error:

```
$ python3 examples/basic_example.py
List Trainer: [#######             ] 33%Traceback (most recent call last):
  File "examples/basic_example.py", line 12, in <module>
    "Your flight has been booked."
  File "/usr/local/lib/python3.7/site-packages/chatterbot/trainers.py", line 110, in train
    statement = self.get_or_create(text)
  File "/usr/local/lib/python3.7/site-packages/chatterbot/trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
AttributeError: 'ChatBot' object has no attribute 'find'
```

**Comment by gunthercox** [comment]
@MartinDelille I see in your trace that the `get_or_create` method in `trainers.py` is where the error with the `find` method is coming from.

Could I suggest making the change in `trainers.py` so we can fix this problem at the source for all of the example programs?

**Comment by MartinDelille** [comment]
Ok I found a way by using the following command but I still have an error:

```
$ python -m examples.basic_example
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/martin/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
List Trainer: [#######             ] 33%Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/martin/dev/clone/ChatterBot/examples/basic_example.py", line 12, in <module>
    "Your flight has been booked."
  File "/Users/martin/dev/clone/ChatterBot/chatterbot/trainers.py", line 107, in train
    statement_search_text = self.tagger.get_bigram_pair_string(text)
  File "/Users/martin/dev/clone/ChatterBot/chatterbot/tagging.py", line 80, in get_bigram_pair_string
    sentence_detector = load_data('tokenizers/punkt/english.pickle')
  File "/usr/local/lib/python3.7/site-packages/nltk/data.py", line 868, in load
    opened_resource = _open(resource_url)
  File "/usr/local/lib/python3.7/site-packages/nltk/data.py", line 993, in _open
    return find(path_, path + ['']).open()
  File "/usr/local/lib/python3.7/site-packages/nltk/data.py", line 699, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/Users/martin/nltk_data'
    - '/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/nltk_data'
    - '/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/share/nltk_data'
    - '/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
```

**Comment by gunthercox** [comment]
There are several ways to make your code use the cloned code instead of the installed package. One easy way is to move the python file to be in the same directory as the `chatterbot` module directory that you've downloaded. Python will check for things to import in the current directory before it looks for installed modules.

Another option you could use is to install the downloaded code after making a change. This can be done by running `pip install . --upgrade` from within the directory that contains `setup.py`.

***

To resolve the second error message you encountered, just follow the instructions it printed out.
`python3 -c 'import nltk; nltk.download("punkt")'` (just a one-line version of the code it provided) will download the `punkt` data corpus from NLTK.

**Comment by MartinDelille** [comment]
@gunthercox Yes the `nltk.download` succeeds:

```
$ python3 -c 'import nltk; nltk.download("punkt")'
[nltk_data] Downloading package punkt to /Users/martin/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
```

Unfortunately I still have the following error:

```
$ python basic_example.py
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/martin/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
List Trainer: [#######             ] 33%Traceback (most recent call last):
  File "basic_example.py", line 12, in <module>
    "Your flight has been booked."
  File "/Users/martin/dev/clone/ChatterBot/chatterbot/trainers.py", line 107, in train
    statement_search_text = self.tagger.get_bigram_pair_string(text)
  File "/Users/martin/dev/clone/ChatterBot/chatterbot/tagging.py", line 93, in get_bigram_pair_string
    pos_tags.extend(pos_tag(words))
  File "/usr/local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 161, in pos_tag
    tagger = _get_tagger(lang)
  File "/usr/local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 107, in _get_tagger
    tagger = PerceptronTagger()
  File "/usr/local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 144, in __init__
    find('taggers/averaged_perceptron_tagger/' + PICKLE)
  File "/usr/local/lib/python3.7/site-packages/nltk/data.py", line 699, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')

  Attempted to load taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle

  Searched in:
    - '/Users/martin/nltk_data'
    - '/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/nltk_data'
    - '/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/share/nltk_data'
    - '/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by gunthercox** [comment]
It looks like you are still missing some of the prerequisite NLTK data. Take a look at the latest error message, notice that it is now asking for the `averaged_perceptron_tagger` to be downloaded.

**Pull request closed without merging**
