### PR TITLE
Avoid import chatterbot in __init__.py when the loaded script is setu…

### PR DESCRIPTION
**Pull request by dannofx**
Hello, I had a problem installing Chattebot from `setup.py`:

```
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    version = __import__('chatterbot').__version__
  File "/Users/danno/ChatterBot/chatterbot/__init__.py", line 1, in <module>
    from .chatterbot import ChatBot
  File "/Users/danno/ChatterBot/chatterbot/chatterbot.py", line 2, in <module>
    from .adapters.storage import StorageAdapter
  File "/Users/danno/ChatterBot/chatterbot/adapters/storage/__init__.py", line 2, in <module>
    from .jsondatabase import JsonDatabaseAdapter
  File "/Users/danno/ChatterBot/chatterbot/adapters/storage/jsondatabase.py", line 4, in <module>
    from jsondb import Database
ImportError: cannot import name 'Database'
```

It was due to `setup.py` imports Chatterbot module (`__init__.py`) to get the author, version and name for the installation and since dependencies are not installed yet, the script gets the above error.

I'm new to python and I don't know if this commit is the best solution for the problem, but if not, I would appreciate any other fix, because Chatterbot will be a dependency to a project I'm working on :).

### CODE REVIEW

**Comment by gunthercox** [comment]
The practice of using imports within init files is rather common in python projects. I've never received a report about this issue before so I'm wondering if the issue have been caused by something else.

Just to be clear, you mentioned that you installed the module using `setup.py`, I'm guessing this means you **did not** use pip to install the package (`pip install chatterbot`)?

**Comment by dannofx** [comment]
Thaks for your reply.

Yes, I didn't use pip, it's becauses I added chatterbot as a install requirement in my project. I have another `setup.py` script that looks like this:

```
#!/usr/bin/env python
from setuptools import setup
...
setup(name='tgbot',
    ...
    install_requires=['chatterbot'],
    ...

    )
```

I'm did some tests on a machine that doesn't have any chatterbot dependency installed (fuzzywuzzy, jsondatabase, nltk, pymongo, etc), when I ran `python3 setup.py install` using my script I got the following output when `setuptools` tried to process chatterbot as a dependency:

```
Installed /usr/local/lib/python3.4/dist-packages/tgbot-0.1-py3.4.egg
Processing dependencies for tgbot==0.1
Searching for chatterbot
Reading https://pypi.python.org/simple/chatterbot/
Best match: ChatterBot 0.3.6
Downloading https://pypi.python.org/packages/cd/0f/55dbbb00a8b913a6c3f35e2185ca3fde368fc01a67a93c78fe3866f59ecb/ChatterBot-0.3.6.tar.gz#md5=7ef111ac05115d51cbe4a123e564e12f
Processing ChatterBot-0.3.6.tar.gz
Writing /tmp/easy_install-g8jhui_7/ChatterBot-0.3.6/setup.cfg
Running ChatterBot-0.3.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-g8jhui_7/ChatterBot-0.3.6/egg-dist-tmp-pb7q5e6h
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-g8jhui_7/ChatterBot-0.3.6/setup.py", line 7, in <module>
    import sys
  File "/tmp/easy_install-g8jhui_7/ChatterBot-0.3.6/chatterbot/__init__.py", line 1, in <module>
  File "/tmp/easy_install-g8jhui_7/ChatterBot-0.3.6/chatterbot/chatterbot.py", line 2, in <module>
  File "/tmp/easy_install-g8jhui_7/ChatterBot-0.3.6/chatterbot/adapters/storage/__init__.py", line 2, in <module>
  File "/tmp/easy_install-g8jhui_7/ChatterBot-0.3.6/chatterbot/adapters/storage/jsondatabase.py", line 4, in <module>
ImportError: No module named 'jsondb'

```

From the log I observed that `setuptools` downloaded `ChatterBot-0.3.6.tar.gz` and tried to install it using its `setup.py` file, but since it imported chatterbot (loads `__init__.py`) to get `__author__`, `__email__` and `__version__` variables it crashed because when `__init__.py` executed the instruction `from .chatterbot import ChatBot` it couldn't find jsondb module due to it's wasn't installed yet.

After this problem, I decided to download chatterbot directly from the github repository and install it using its `setup.py` file and see what happens. The installation output was the same that the shown above (with the same error). So, I modified  the `__init__.py` file in chatterbot to avoid the import if the executed file is `setup.py`:

```
import os
import sys

script_name = os.path.basename(sys.argv[0])

if script_name != 'setup.py':
        from .chatterbot import ChatBot

__version__ = "0.3.7"
__author__ = "Gunther Cox"
__email__ = "gunthercx@gmail.com"
```

And the installation using `setup.py` was successful.

In another hand, if I install chatterbot first using `pip install chatterbot` I don't get any error and everything is ok, but I would like it could be installed using `install_requires` in my `setup.py` file to automate this process.

**Comment by gunthercox** [comment]
Ok, I've tested this locally and it looks good to me. Thank you for the pull request.

**Comment by dannofx** [comment]
Thanks to you.

**Pull request merged**
