### PR TITLE
initial commit for CouchDBTrainer

### PR DESCRIPTION
**Pull request by galeej**
Created a couchdb trainer that will let the chatterbot train from a set of couchdb documents.

This enables people who use a couchdb database to automatically train the chatbot from their documents (rather than resorting to different dbs).

Things that you will have to do from a db end:
1. Create your training dataset with doc_type:'chatterbot'
2. Create a map function that will emit key value paris with values in the same format as the json corpus.

### CODE REVIEW

**Comment by gunthercox** [comment]
Hi @galeej thank you for submitting this pull request for #659. Unfortunately I can't merge it in to the project because it lacks comprehensive unit test coverage and documentation. With the addition of those two elements I believe this could be a candidate feature addition.

**Comment by galeej** [comment]
Hi @gunthercox  could you let me know what all I should do vis-a-vis unit testing and documentation (should I add more comments or should i give you a more detailed documentation in word or something)?

**Comment by vkosuri** [comment]
@galeej This link we show how to run unittests under chatterbot http://chatterbot.readthedocs.io/en/stable/testing.html

The MangoDBTestAdapter will tell how to write a testcase for your new adapter https://github.com/gunthercox/ChatterBot/blob/master/tests/storage_adapter_tests/test_mongo_adapter.py#L7

**Comment by vkosuri** [comment]
And also the tests are faling, please run chatterbot unitests before pushing 
``` Bash
nosetests tests/logic_adapter_tests
```

And more documentation about Python [Unittest](https://docs.python.org/2/library/unittest.html) framework

**Comment by galeej** [comment]
thanks.  Will finish and push again.

**Comment by galeej** [comment]
Hi All,

my apologies for the delay... I've been a bit busy with exams.  I'll have this done by the end of the month.

**Pull request closed without merging**
