### PR TITLE
SVO logic adapter

### PR DESCRIPTION
**Pull request by DarkmatterVale**
In this PR I added a Subject-Verb-Object triplet based logic adapter. This uses a library that I created, regex4dummies, to identify the dependencies within a sentence. Although very simple, it should still work well as a logic adapter.

### CODE REVIEW

**Comment by gunthercox** [comment]
The new adapter looks great! I also just added you to the git repo so you can directly create new branches and push to the repo if you want to.

**Comment by gunthercox** [comment]
Also, you should now have access edit the project wiki. Would you mind adding a brief description for the new logic adapter?
https://github.com/gunthercox/ChatterBot/wiki/Logic-adapters

**Comment by DarkmatterVale** [comment]
Thanks you!

Sure! I will add a quick overview ASAP.

**Comment by DarkmatterVale** [comment]
I just added a brief description. Is that what you were looking for? Or should I give a little more detail?

**Comment by gunthercox** [comment]
That looks good. Thank you.

**Pull request merged**
