### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by JulianoEngineer**
Creating readme in portuguese. I don't know the best form to do this, because of this  I have created a new directory called "support" for add files in portuguese.

### CODE REVIEW

**Comment by JulianoEngineer** [comment]
If you send me the font name of main banner, I translate the image.

**Comment by gunthercox** [comment]
I created the banner using GIMP, it appears that I no longer have the original `.xcf` file for the banner (which would have made editing it much easier), but the font in GIMP was called **Courier 10 Pitch**.

**Comment by gunthercox** [comment]
Also, the only other github project I could find that has additional readme languages appears to just include them in the base directory of the project: https://github.com/tiimgreen/github-cheat-sheet/blob/master/README.md

**Comment by JulianoEngineer** [comment]
Main Banner in portuguese to aprove.

chatterbot_pt

**Comment by gunthercox** [comment]
Looks great :+1: Thank you.

**Comment by gunthercox** [comment]
Sorry, looks like I forgot to hit merge on this :smile:

**Pull request merged**
