### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by kelonye**

### CODE REVIEW

**Comment by vkosuri** [comment]
@kelonye Thanks for PR, I believe this very specific to a user chatterbot app. I felt this PR should goes [chatterbot-tricks](https://github.com/vkosuri/chatterbot-tricks).

Any comments @gunthercox

**Comment by gunthercox** [comment]
I agree with @vkosuri. I like the idea of having these instructions available to point people to if they have questions. However I'm not sure how useful a Docker container is for the typical Python developer who wants to use or contribute to this project.

**Comment by kelonye** [comment]
Just thought docker is preferred over virtualenv nowadays. Nice project btw ..

**Comment by vkosuri** [comment]
@kelonye if you are interested make use of please PR, please submit a PR chatterbot-tricks.

**Pull request closed without merging**
