### PR TITLE
best_match based on LevenshteinDistance become faster

### PR DESCRIPTION
**Pull request by echoocking**
restructure the best_match implement based on LevenshteinDistance. 
### basic info
storage_adapter="chatterbot.storage.MongoDatabaseAdapter"
db.statements.count() --> 55679
### appearance
i write a flask app. after trained talking bot, i get response may cost 15s+
so i restructure some code to improve efficiency
### algorithm before:
use for loop to every other_statement to compare.
get the score,and use it to judge which is the max.
seems too slowly
### after
use generator to get all statements score.
and get python build_in function max to get the best_match statement.

### conclusion
get response time reduced to 4-5 s

if i miss sth, please let me know.
thank you for your view~

### CODE REVIEW

**Comment by vkosuri** [comment]
@echoocking Thank for your contribution, the tests are failing https://travis-ci.org/gunthercox/ChatterBot/jobs/314024538#L567

**Comment by echoocking** [comment]
I know , i will fix it. Beacuse i  do not check  the test code. 
after i pull , exec 'make all'.

======================================================================
ERROR: test_best_match (tests_django.integration_tests.test_logic_adapter_integration.LogicIntegrationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/echoocking/projects/ChatterBotPr/tests_django/integration_tests/test_logic_adapter_integration.py", line 35, in test_best_match
    response = adapter.process(statement1)
  File "/Users/echoocking/projects/ChatterBotPr/chatterbot/logic/best_match.py", line 49, in process
    closest_match = self.get(input_statement)
  File "/Users/echoocking/projects/ChatterBotPr/chatterbot/logic/best_match.py", line 35, in get
    confidence = [_ for _ in self.compare_statements(input_statement, statement_list)]
  File "/Users/echoocking/projects/ChatterBotPr/chatterbot/comparisons.py", line 12, in __call__
    return self.compare(statement_a, statement_b)
  File "/Users/echoocking/projects/ChatterBotPr/chatterbot/comparisons.py", line 63, in compare
    if not statement.text or not other_statement.text:
AttributeError: 'QuerySet' object has no attribute 'text'

----------------------------------------------------------------------
Ran 81 tests in 28.892s

FAILED (errors=1)
Destroying test database for alias 'default'...
make: *** [all] Error 1

**Comment by echoocking** [comment]
seems every distance comparison algorithm should be adjust , the test will be passed...

**Comment by gunthercox** [comment]
@echoocking Is this pull request still in progress?

If so, can you provide the method that you used to test the execution time for the speed improvement so that we may test it?

**Comment by echoocking** [comment]
@gunthercox  I commit the code at this pr... or where should i give u this method?
Sorry,i am new to become a contributor

**Comment by echoocking** [comment]
What I do is to improve the matching algorithm.Use the generator instead of a for loop.Code is short and clear.Didn't pass the test because the modified this method in other places also have a call.

**Comment by zxsimple** [comment]
@echoocking would you please check whether this is the same as [https://github.com/gunthercox/ChatterBot/pull/1158](https://github.com/gunthercox/ChatterBot/pull/1158)

**Comment by echoocking** [comment]
@zxsimple The way I adjusted out data post-processing.Did not take into account the issue of library

**Comment by gunthercox** [comment]
@echoocking Thank you for taking the time to work on this. I'm going to close this ticket off because tests are not passing and I don't see any recent commit history. Feel free to resubmit if you are still interested in contributing.

**Pull request closed without merging**
