### PR TITLE
Unit conversion adapter

### PR DESCRIPTION
**Pull request by manoelrui**
Pull request to feature #1170.

### CODE REVIEW

**Comment by vkosuri** [comment]
Thanks @manoelrui the tests are failing due to 

`` 
./chatterbot/logic/__init__.py:9:1: F401 '.unit_conversion_adapter.UnitConversion' imported but unused
ERROR: InvocationError for command '/home/travis/build/gunthercox/ChatterBot/.tox/lint/bin/flake8' (exited with code 1)
```

**Comment by manoelrui** [comment]
@vkosuri I don't know how exactly fix it, because if I remove this import in ".**/chatterbot/logic/__init__.py**" the unit test class **UnitConversionTests** that I created doesn't identify the import "**from chatterbot.logic import UnitConversion**" to test the **UnitConversion** class. Hence, It will fail all unit tests of **UnitConversionTests**.

**Comment by manoelrui** [comment]
@vkosuri There is just a benchmark test that fails because the maximum duration time, a any idea to fix it ? Is it reasonable solution to raise the maximum duration time ?

**Comment by gunthercox** [comment]
@manoelrui Just a heads up, you can run the linting checks locally using either the commands `flake8` or `tox -e lint`.

**Comment by manoelrui** [comment]
@gunthercox  and @vkosuri , thank you for you help.

**Comment by vkosuri** [comment]
@manoelrui Thank you very much, give me some time

**Comment by manoelrui** [comment]
@gunthercox  and @vkosuri Can I add more improvements like: doc, source code example, support to another unit metrics and unit tests ?

**Comment by vkosuri** [comment]
@gunthercox Master any update about this PR?

**Comment by gunthercox** [comment]
@manoelrui This looks very cool. If I merge this in, would it be okay if I request your assistance for answering questions and reviewing pull requests when other developers contribute to it?

**Pull request merged**
