### PR TITLE
compare statements using list comprehension

### PR DESCRIPTION
**Pull request by vkosuri**
This PR will address issue https://github.com/gunthercox/ChatterBot/issues/679

***

Observed some significant changes are observed with my machine and other previous PRs

https://travis-ci.org/gunthercox/ChatterBot/jobs/228723891#L409, this execution took ``Ran 340 tests in 16.152s``

With New approach took ``Ran 340 tests in 10.266s``

### CODE REVIEW

**Comment by vkosuri** [comment]
@yeshoujquery, @whm2300 if you want you could try with this patch, let me know is there any improvement with patch?

**Comment by yeshoujquery** [comment]
@vkosuri  Mongodb 373753 data time-consuming 89ms, relatively fast before, but can it be faster? Seconds out of that kind?

**Comment by vkosuri** [comment]
Failed due to network issue https://travis-ci.org/gunthercox/ChatterBot/jobs/232412009#L213, @gunthercox do you want me re-run tests?

**Comment by gunthercox** [comment]
@vkosuri, I manually restarted the test.

**Comment by vkosuri** [comment]
@gunthercox and @yeshoujquery any further updates?

**Comment by yeshoujquery** [comment]
@vkosuri The latest changes I have merged into my local, i5,8g, or previous data structures and forms, and the corresponding time is 92ms, with no obvious improvement

results of enforcement

**Comment by vkosuri** [comment]
@yeshoujquery I think i am converted all loops into iterators for some better process. i.e *315831ms (315.831sec)* reduced to *92ms(0.092sec)* the response what you are seeing is within in a sec.

I am not familiar with other chatbots, could you please let me know what is the idea time to response from chatbot, if we trained 2M data?

**Comment by yeshoujquery** [comment]
92ms doesn't feel like it. The robot I made with tensorflow reflects the speed of milliseconds. Address: [http://bot.mxgome.com](http://bot.mxgome.com), I still prefer chatterbot.

**Comment by yeshoujquery** [comment]
@vkosuri 92ms doesn't feel like it. The robot I made with tensorflow reflects the speed of milliseconds. Address: [http://bot.mxgome.com](http://bot.mxgome.com), I still prefer chatterbot.

**Comment by vkosuri** [comment]
I further nailed down the percentage of process utilization, it look something like this

image

**Comment by yeshoujquery** [comment]
@vkosuri I checked the source code, and I feel it is to take the data after the processing, it is relatively slow, take data and results show relatively fast, matching accuracy there slow

**Comment by yeshoujquery** [comment]
@vkosuri @gunthercox Is the chatterbot author not maintained?

**Comment by vkosuri** [comment]
@gunthercox Master, i am done with my changes, let me know any comments/suggestions on this PR? Any improvement thoughts?

**Comment by vkosuri** [comment]
@yeshoujquery if you want give a try to test this PR, i see some improvement from previous

**Comment by zhantongz** [comment]
I got an error TypeError: object of type 'map' has no len() when trying

**Comment by vkosuri** [comment]
Look into failures

**Comment by vkosuri** [comment]
It's dedent issue https://travis-ci.org/gunthercox/ChatterBot/jobs/235183780#L429

**Comment by vkosuri** [comment]
@zhantongz could try now?

**Comment by yeshoujquery** [comment]
@vkosuri I've lost confidence in chatterbot and handled too little data @gunthercox The author is not very well maintained, right?

**Comment by vkosuri** [comment]
@gunthercox Master, any updates? do you want me close this issue or can I rework?

**Comment by zhantongz** [comment]
It works but the improvement is minimal for me.

**Comment by vkosuri** [comment]
I am closing this PR, It's not an optimal solution

**Pull request closed without merging**
