### PR TITLE
response into JSON object

### PR DESCRIPTION
**Pull request by vkosuri**
Somehow the current djanog response isn't converting into JSON object, it always returns. https://github.com/gunthercox/ChatterBot/issues/497 issue will fix this error.

### CODE REVIEW

**Comment by vkosuri** [comment]
@gunthercox sure will work on those two tests, One question, where do i need to add these test either in django example app [tests ](https://github.com/gunthercox/ChatterBot/blob/master/examples/django_app/tests/test_example.py)or in [django_tests](https://github.com/gunthercox/ChatterBot/blob/master/tests_django/test_views.py)

**Comment by gunthercox** [comment]
These tests should be in the `django_tests` directory. You can run these django-specific tests with:

```
python runtests.py
```

**Comment by vkosuri** [comment]
@gunthercox i am little busy with other tasks, It may take another day or two, Could you please let me are there any ETAs for new release?

**Comment by gunthercox** [comment]
I don't have an ETA yet, I'm possibly looking to do one either this weekend or next week.

**Comment by vkosuri** [comment]
appologies for many failures, needs to learn  ``python3`` 📦

**Comment by gunthercox** [comment]
This looks great, thank you for adding the test cases. They help make sure that this functionality never breaks again in the future.

**Pull request merged**
