### PR TITLE
CharField to TextField

### PR DESCRIPTION
**Pull request by vkosuri**
Closes https://github.com/gunthercox/ChatterBot/issues/921

Reference: https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.CharField

### CODE REVIEW

**Comment by vkosuri** [comment]
@gunthercox I try to make migrations on django_chatterbot it was saying no changes found. I tried like this. Any tips how do migration on django_chatterbot?

``` Bash
(env)vkosuri@vm-vkosuri:~/ChatterBot$ python examples/django_app/manage.py migrate django_chatterbot
Operations to perform:
  Apply all migrations: django_chatterbot
Running migrations:
  No migrations to apply.
(env)vkosuri@vm-vkosuri:~/ChatterBot$ python examples/django_app/manage.py makemigrations django_chatterbot
No changes detected in app 'django_chatterbot'
```

**Comment by gunthercox** [comment]
I'll look into this and see if I can recreate the issue. I'll let you know what I have to do to get them to generate.

**Comment by vkosuri** [comment]
This PR will solve this problem https://github.com/gunthercox/chatterbot-corpus/pull/36

**Comment by vkosuri** [comment]
@gunthercox Thanks fix this issue, could you please let me know how to generate django_chatterbot migrations?

**Comment by gunthercox** [comment]
These are the steps. They work but I wish I had easier ones.

1. cd ChatterBot
2. pip install . --upgrade
3. cd examples/django_app/
4. python manage.py makemigrations
5. Navigate to the Python package install directory and cut and paste the new migration into the migrations directory of your local project.

**Pull request closed without merging**
