### PR TITLE
fix error in docs:no need for suffix .db according to source code

### PR DESCRIPTION
**Pull request by vimerzhao**
1. according to `./chatterbot/storage/sql_storage.py`, no need fox suffix
2. use `sys.path[0]`, otherwise the relative path will change with location where python interpreter start

### CODE REVIEW

**Comment by vkosuri** [comment]
@vimerzhao I am unable to figured it out, could you please let me know failure points or improvements?

**Comment by vimerzhao** [comment]
@vkosuri 
for example,if I use`bot = ChatBot("Name", database="./databse.db")` according to docs,`database.db.db` will be generated because of `./chatterbot/storage/sql_storage.py` add `.db` default.
another problem,if I use `bot = ChatBot("Name", database="./databse.db")` in `~/dir1/dir2/demo.py`,
```
~/dir1 $ python dir2/demo.py
``` 
would generated databse file in `dir1`;
```
~/dir1/dir2 $ python demo.py
```
wolud generated database file in `dir2`
this is confused!use `sys.path[0]` can avoid it.
sorry for my pool english.

**Comment by vkosuri** [comment]
Gotcha

https://github.com/gunthercox/ChatterBot/blob/68527223db52c39cbb94393cdf313f39485c5856/chatterbot/storage/sql_storage.py#L55

**Comment by vimerzhao** [comment]
I agree with you !!!  However,I can't pass all tests when I tried to change sqladapter due to
```python
    def test_set_database_name(self):
        adapter = SQLStorageAdapter(database='test')
        self.assertEqual(adapter.database_uri, 'sqlite:///test.db')
```
in `./tests/storage_adapter_tests/test_sqlalchemy_adapter.py` .Therefore, I fixed the docs.
I am a beginner,but I like to fix the problem. @gunthercox

**Comment by gunthercox** [comment]
@vimerzhao Thank you. I'll check over the code and try to post something to help guide you through the necessary changes. I'll post the information as soon as I can but you might not hear from me until later today or tomorrow.

**Comment by vimerzhao** [comment]
@gunthercox I modify the code and commit it.This is my first time to contribute code like this,**thanks** for you guidance!

**Comment by gunthercox** [comment]
I believe the change you'd need to make is just dropping the ".db" from the end of this line in sql_storage.py

```python
self.database_uri = "sqlite:///" + database_name + ".db"
```

[chatterbot/storage/sql_storage.py#L55](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/storage/sql_storage.py#L55)

**Comment by vimerzhao** [comment]
that can't pass the test case
```
    def test_set_database_name(self):
        adapter = SQLStorageAdapter(database='test')
        self.assertEqual(adapter.database_uri, 'sqlite:///test.db')
```
[/ChatterBot/tests/storage_adapter_tests/test_sqlalchemy_adapter.py#L34](https://github.com/gunthercox/ChatterBot/blob/d20263aef280428def71dc9d4e8aa12a3b5c1f7f/tests/storage_adapter_tests/test_sqlalchemy_adapter.py#L34)
@gunthercox

**Comment by gunthercox** [comment]
Hi @vimerzhao, I ended up making some changes just to verify what would be needed to resolve this and ended up making a pull request. I apologize for taking away your chance to contribute code to the project but I hope to see pull requests from you in the future. Thank you again for your help in tracking down this bug.

See #933 for details on the changes.

**Pull request closed without merging**
