### PR TITLE
Added corpus training data on computers

### PR DESCRIPTION
**Pull request by mayank11196**
Added corpus training data on the topic of computers in english language.

### CODE REVIEW

**Comment by mayank11196** [comment]
Hi @gunthercox  I can see that you have aproved my pull request but i cant see it on the master branch that is i cant see it merged with the master. I'm relatively new to open source contribution so if you could tell me what to do now i'll really appreciate it. I have lots of corpus training data on other topics that i want to commit.
Thanks.

**Comment by gunthercox** [comment]
Hi @mayank11196, thank you very much for your pull request. I apologize about the delay in merging it. I'm actually in the process of moving ChatterBot's data corpus to it's own repository: https://github.com/gunthercox/chatterbot-corpus

Would you mind submitting your pull request there instead?

**Comment by mayank11196** [comment]
No not at all. Infact have already created a pull request on that repository.
Thanks for the guidance.

**Comment by gunthercox** [comment]
Thank you, I have merged your contribution to the `chatterbot-corpus` repository.

**Pull request closed without merging**
