### PR TITLE
Add link from examples to setup instructions

### LINKED ISSUE #1528: Document example setup
For a non python developer like me it is not very easy to understand how to set up the examples.

I would be happy to document this but I would need some basic info. For example, I first installed ChatterBox given following command:

```
pip install chatterbox
```

Unfortunately, when I try to run `basic_example` it fails:

```
$ python basic_example.py
List Trainer: [#######             ] 33%Traceback (most recent call last):
  File "basic_example.py", line 12, in <module>
    "Your flight has been booked."
  File "/usr/local/lib/python3.7/site-packages/chatterbot/trainers.py", line 110, in train
    statement = self.get_or_create(text)
  File "/usr/local/lib/python3.7/site-packages/chatterbot/trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
AttributeError: 'ChatBot' object has no attribute 'find'
```

### PR DESCRIPTION
**Pull request by gunthercox**
Closes #1528

### CODE REVIEW

**Comment by MartinDelille** [comment]
You edit doesn't really help but maybe it is because the lack of support of github for RST?

screenshot 2019-01-15 21 11 30

**Comment by MartinDelille** [comment]
Ok great I was able to make it work! Thank you for your kind help!

**Comment by gunthercox** [comment]
Thank you as well, getting feedback on things like this is extremely helpful.

**Comment by MartinDelille** [comment]
Now that the basic example works, I will be able to go further with my tests and won't hesitate to give you more feedback!

Being able to manipulate an intelligent bot like that with so little code is a must when you're not an AI expert!

**Pull request merged**
