### PR TITLE
New remote MongoDB adapter.

### PR DESCRIPTION
**Pull request by sgoblin**
The old adapter for MongoDB could not connect to remote databases, so I forked it into a new adapter and added code to make work with remote DBs.

### CODE REVIEW

**Comment by sgoblin** [comment]
I'm not sure how to add tests for this, as it would require setting up a remote MongoDB. I could set up a MongoLab DB for this, but @gunthercox would have to add the password to the .travis.yml file as encrypted.

**Comment by kevin-brown** [comment]
This would probably be better integrated into the existing MongoDB adapter, with the database location being a configuration option (defaulting to localhost).

**Comment by sgoblin** [comment]
Actually, I think you're right. How do you add defaults for **kwargs?

**Comment by gunthercox** [comment]
@sgoblin You can add a default for kwargs like this:

```python
something = kwargs.get("some_key", "default_value")
```

**Pull request closed without merging**
