### PR TITLE
Adding ArangoDB Storage Adapter

### PR DESCRIPTION
**Pull request by iamhssingh**
I have added ArangoDB storage adapter.

Example of using ArangoDB:
```Python
bot = ChatBot(
        "ChatBot Name",
        storage_adapter='chatterbot.storage.ArangoStorageAdapter',
        logic_adapters=[
            "chatterbot.logic.MathematicalEvaluation",
            "chatterbot.logic.TimeLogicAdapter",
            "chatterbot.logic.BestMatch"
        ],
        input_adapter="chatterbot.input.TerminalAdapter",
        output_adapter="chatterbot.output.TerminalAdapter",
        username='chatterbot', # This is the username to be used to connect with Arango (required)
        password='chatterbot', # This is the password. (required)
        database_name='chatterbot', # This is the database_name. (default: chatterbot-database)
        collection='statements' # This is the collection. (default: statements)
    )
```

### CODE REVIEW

**Comment by iamhssingh** [comment]
Well, I have not added a test case. I don't know if I should.

Sorry I had to make 5 commits. New in Git. 
-> Added ArangoDB storage adapter
-> Added ArangoDB import in __init__.py
-> Removed error that PyCharm made in __init__.py by AutoRearranging
-> Added python-arango in requirements.txt (wrong commit title)
-> Corrected commit title and version >=

**Comment by iamhssingh** [comment]
I don't know why tests are failing. I ran on my computer, all ran fine. I can't find the error in online test except for some network error!

**Comment by vkosuri** [comment]
Its pep8 failure at chatterbot/storage/arangodb.py:134:42: W503 line break before binary operator

**Comment by iamhssingh** [comment]
Pfft.. Can anyone check again for me the error? It's in Python 2.7!

**Comment by vkosuri** [comment]
It seems to me a network issue, i have restarted the job again, hope it will pass

**Comment by iamhssingh** [comment]
I will try to add test. But the test requires to setup an ArangoDB with user and password. I have no idea how to do that!

How to Use documentation, yes I can. I don't know where to put them in project.

**Comment by vkosuri** [comment]
see this example https://github.com/gunthercox/ChatterBot/blob/master/tests/storage_adapter_tests/test_mongo_adapter.py

**Comment by siorikitajima** [comment]
#773

**Comment by iamhssingh** [comment]
@vkosuri  In MongoDB you don't need any `username` or `password`. Also in Mongo, `database` and `collection` is created dynamically. This is not same in Arango. `username`, `password` and pre-set `database` and `collection` is required. Should I create `test_arango_adapter.py` with sample `username` and `password`?

**Comment by iamhssingh** [comment]
@vkosuri Hey, can you check and let me know if documentation and how to do that I added are fine?

I am working on adding `Test Cases`.

**Comment by vkosuri** [comment]
@iamhssingh so far looks good to me, I never used aragon db i need to try something on machine to explore more, I feel @gunthercox needs review this PR

**Comment by vkosuri** [comment]
@gunthercox Master any comments

**Comment by vkosuri** [comment]
I'll total agree with @gunthercox

**Comment by iamhssingh** [comment]
@gunthercox Sure. 

- Considering the High Demand: MultiModel database will actually make ChatterBot highly efficient. The concept of edges is really amazing. In fact, with the help of edges, you can actually create a Graph which can make ChatterBot reply as per the **context** of the chat. 

- That being said, yes you are right. There is need to regular maintenance of code with additional features that are coming up. But the storage adapter is only there for storage, right? 

- About third party Python package, how do you mean the package? A package for ChatterBot. Or a package for Python connectivity. Because I have already used a 3rd party package for Python connectivity based on which I have written the whole code. 

- The automated testing, I actually have no idea how to set it up. I have copied and pasted the MongoDB testing but unlike MonogoDB, ArangoDB requires a preset userid, password and database with collection. So, a little help in setting one will be awesome.

- Future changes that are needed: I have already written in ToDo that I need to implement a query system to enable some query features. But currently I am working on implementing the edges and creating Graph that will make ChatterBot more efficient.

**Comment by gunthercox** [comment]
@iamhssingh  The third party package would be a Python package for ChatterBot (something that could be installed with a command such as `pip install chatterbot-arangodb-storage`. It's fairly easy to create an additional module that can be installed to add functionality to ChatterBot. There are a few existing examples of this, for instance `chatterbot-weather` is a logic adapter that allows a chat bot to answer weather related questions.

If you create a new GitHub repository and add me to it I would be more than happy to help set this up and help get automated testing to work.

**Comment by iamhssingh** [comment]
@gunthercox @vkosuri Sorry I was away because of some college issues. 

How do I create this new adapter to package it as installable? I see that my existing adapter need huge updates. I will add you to github project. Please guide me.

**Comment by vkosuri** [comment]
sure

**Comment by gunthercox** [comment]
@iamhssingh Got the invite. I'll try to have a pull request for your repository with some package setup this weekend.

**Pull request closed without merging**
